[package]
name = "av-scenechange"
version = "0.7.2"
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
edition = "2018"
description = "Estimates frames in a video where a scenecut would be ideal"
license = "MIT"
repository = "https://github.com/rust-av/av-scenechange"

[dependencies]
anyhow = "1.0.56"
y4m = "0.7.0"
clap = { version = "3.1.6", optional = true }
serde = { version = "1.0.123", optional = true, features = ["derive"] }
serde_json = { version = "1.0.62", optional = true }
# rav1e = { git = "https://github.com/redzic/rav1e", branch = "zerocopy", default-features = false, features = [
#     "asm",
#     "scenechange",
#     "threading",
# ] }
rav1e = { path = "../rav1e", default-features = false, features = [
    "asm",
    "scenechange",
    "threading",
] }
log = { version = "0.4.14", optional = true }
console = { version = "0.15", optional = true }
fern = { version = "0.6", optional = true }
rust_hawktracer = "0.7.0"
ffmpeg = { package = "ffmpeg-next", version = "5.0.3" }
av-metrics-decoders = { path = "../av-metrics/av_metrics_decoders", features = [
    "ffmpeg",
] }

[features]
default = ["binary", "vapoursynth_new_api"]
binary = ["clap", "serialize"]
serialize = ["serde", "serde_json"]
devel = ["log", "console", "fern"]
tracing = ["rust_hawktracer/profiling_enabled"]
vapoursynth_new_api = ["av-metrics-decoders/vapoursynth_new_api"]

[[bin]]
name = "av-scenechange"
path = "src/main.rs"
required-features = ["binary"]
